version: 2.1

orbs:
  docker: circleci/docker@0.5.20
jobs:
  meterian:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: |
            docker run --rm \
            --volume ${PWD}:/workspace \
            meterian/cli --oss

workflows:
  version: 2
  commit-workflow:
    jobs:
      - meterian
